import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import NavBar from "@/components/NavBar";
import SideNav from "@/components/SideNav";
import Background from "@/components/Background";
import dynamic from "next/dynamic";
// import WorldGlobe from "@/components/Globe";
const WorldGlobe = dynamic(() => import("@/components/Globe"), { ssr: false });

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Energenuis",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider attribute="class" defaultTheme="dark" enableSystem disableTransitionOnChange>
          <NavBar />
          <SideNav />
          <Background />
          <WorldGlobe />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
